const complianceService = require('./complianceService');
const auditService = require('./auditService');

function sanitizeCsv(value) {
  if (value === null || value === undefined) return '';
  let str = String(value);
  // Neutralize formula injection
  if (/^[=+\-@\t\r]/.test(str)) {
    str = "'" + str;
  }
  // Escape quotes
  if (str.includes('"') || str.includes(',')) {
    str = `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

const reportService = {
  generateCsv: async (user, filters) => {
    const data = await complianceService.getSummary(user, filters);
    
    let csv = `Report Date,${new Date().toISOString()}\n`;
    csv += `Generated By,${sanitizeCsv(user.name)}\n`;
    csv += `Scope,${sanitizeCsv(JSON.stringify(filters))}\n\n`;

    csv += `Category,Total,Completed,Pending,Overdue,Rate (%)\n`;
    const rows = [
      ['Policies', data.policies.total, data.policies.completed, data.policies.pending, data.policies.overdue, data.policies.rate],
      ['Lessons', data.lessons.total, data.lessons.completed, data.lessons.pending, data.lessons.overdue, data.lessons.rate],
      ['Quizzes', data.quizzes.total, data.quizzes.completed, data.quizzes.pending, data.quizzes.overdue, data.quizzes.rate]
    ];

    for (const row of rows) {
      csv += row.map(sanitizeCsv).join(',') + '\n';
    }

    await auditService.log(user.id, 'EXPORT_REPORT', 'Report', 'CSV', { filters });

    return csv;
  },

  generatePdf: async (user, filters) => {
    const data = await complianceService.getSummary(user, filters);
    // Minimal mock PDF text representation since we don't have a real PDF library installed yet
    const pdfContent = `PDF REPORT\nDate: ${new Date().toISOString()}\nGenerated By: ${user.name}\nFilters: ${JSON.stringify(filters)}\n\nPolicies Rate: ${data.policies.rate}%\nLessons Rate: ${data.lessons.rate}%\nQuizzes Rate: ${data.quizzes.rate}%\n`;
    
    await auditService.log(user.id, 'EXPORT_REPORT', 'Report', 'PDF', { filters });
    
    return pdfContent;
  }
};

module.exports = reportService;
